local TUNING = GLOBAL.TUNING

-- 在TUNING中添加dreadsword需要的值
TUNING.DREADSWORD = {
	DAMAGE = 51,
	PLANAR_DAMAGE = 17,
	USES = 150,
	SHADOW_LEVEL = 3,
    REGEN_MAXRATE = TUNING.ARMOR_DREADSTONE_REGEN_MAXRATE,
    REGEN_MINRATE = TUNING.ARMOR_DREADSTONE_REGEN_MINRATE,
    REGEN_SETBONUS = TUNING.ARMOR_DREADSTONE_REGEN_SETBONUS,
    REGEN_PERIOD = TUNING.ARMOR_DREADSTONE_REGEN_PERIOD,
}
